### ISSUE TITLE
how to use the project?

### ISSUE THREAD

**Issue by weituotian** [remcoros/Direct3DCapture#2]
i do not konw how to do

**Comment by remcoros** [comment]
Hey,

This project is not intended to be used as is.

It is based on https://github.com/spazzarama/Direct3DHook (you should read his blog post to get more insight).

I posted this code online, as I used some ideas/code from OBS (which is GPL licensed). 

So, sorry, this is a reference implementation you can use to get some ideas / examples, but you shouldn't use this as is in an existing project.
